package com.points.backend.db

/**
 * The Points schema as versioned migrations, applied by [MigrationRunner] at startup. Every statement here
 * is deliberately portable across H2 (dev) and Postgres (prod): standard `GENERATED ... AS IDENTITY` (not
 * H2's `AUTO_INCREMENT`), a plain sequence with `NEXTVAL` (native on Postgres, compatibility function on
 * H2), and ordinary indexes.
 *
 * v1 consolidates the schema as it stood when the runner was introduced (#55) — the ledger and catalog
 * tables previously created ad-hoc by the storage constructors, including the #99 hardening (identity
 * `seq`, `point_type_seq` sequence) and the #101 `(owner_id, seq)` pull indexes. Anything after v1 must be
 * a **new** migration; applied migrations are immutable.
 */
val pointsMigrations: List<Migration> = listOf(
    Migration(
        version = 1,
        description = "ledger + catalog: point_event, point_type, point_type_seq, pull indexes",
        statements = listOf(
            """
            CREATE TABLE point_event (
                seq           BIGINT       GENERATED BY DEFAULT AS IDENTITY,
                id            VARCHAR(64)  PRIMARY KEY,
                owner_id      VARCHAR(64)  NOT NULL,
                point_type_id VARCHAR(64)  NOT NULL,
                delta         BIGINT       NOT NULL,
                device_id     VARCHAR(128) NOT NULL,
                created_at    BIGINT       NOT NULL
            )
            """,
            "CREATE INDEX idx_point_event_owner_seq ON point_event (owner_id, seq)",
            """
            CREATE TABLE point_type (
                seq        BIGINT       NOT NULL,
                id         VARCHAR(64)  PRIMARY KEY,
                owner_id   VARCHAR(64)  NOT NULL,
                name       VARCHAR(255) NOT NULL,
                hue        INT          NOT NULL,
                icon       VARCHAR(64)  NOT NULL,
                mode       VARCHAR(32)  NOT NULL,
                step       BIGINT       NOT NULL,
                goal       VARCHAR(32)  NOT NULL,
                target     BIGINT,
                unit       VARCHAR(64)  NOT NULL,
                created_at BIGINT       NOT NULL,
                updated_at BIGINT       NOT NULL,
                deleted_at BIGINT
            )
            """,
            "CREATE INDEX idx_point_type_owner_seq ON point_type (owner_id, seq)",
            "CREATE SEQUENCE point_type_seq",
        ),
    ),
)
